<a href="https://colab.research.google.com/github/hiesenebrg/DeepLearning/blob/main/Forward_Propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X = np.array([[0,0],[0,1],[1,0],[1,1]]) #this is input as x1 and x2
Y = np.array([[0,0,0,1]]).T #this is output as y
X.shape , Y.shape

((4, 2), (4, 1))

In [ ]:
def seg(z):
  return 1/(1+np.exp(-z))

In [ ]:
#no hidden layer weights
weights = 2*np.random.random((2,1))-1
#as we have to take range of both of the weights  from -1 to +1
bias = 2*np.random.random(1)-1
weights , bias

(array([[ 0.9323261],
        [-0.1485848]]),
 array([0.32502766]))

In [ ]:
output0 = X
output = seg(np.dot(output0 , weights)+bias)
#this si the dot mtrix multiplicaion of (2,4) atrix to (1,2) weight matrix
output

array([[0.58054904],
       [0.54399663],
       [0.77857024],
       [0.75189954]])