<a href="https://colab.research.google.com/github/hiesenebrg/DeepLearning/blob/main/Forward_Propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X = np.array([[0,0],[0,1],[1,0],[1,1]]) #this is input as x1 and x2
Y = np.array([[0,0,0,1]]).T #this is output as y
X.shape , Y.shape

((4, 2), (4, 1))

In [ ]:
def seg(z):
  return 1/(1+np.exp(-z))

In [ ]:
#no hidden layer weights
weights = 2*np.random.random((2,1))-1
#as we have to take range of both of the weights  from -1 to +1
bias = 2*np.random.random(1)-1
weights , bias

(array([[ 0.9323261],
        [-0.1485848]]),
 array([0.32502766]))

In [ ]:
output0 = X
output = seg(np.dot(output0 , weights)+bias)
#this si the dot mtrix multiplicaion of (2,4) atrix to (1,2) weight matrix
output

array([[0.58054904],
       [0.54399663],
       [0.77857024],
       [0.75189954]])

In [15]:
#with hidden layers
wh = 2*np.random.random((2,2))-1
bh = 2*np.random.random((1,2))-1
wo = 2*np.random.random((2,1))-1
bo = 2*np.random.random((1,1))-1

In [16]:
wh,bh,wo,bo

(array([[-0.73321851, -0.42895861],
        [ 0.41491719,  0.55794787]]),
 array([[0.67561396, 0.98473211]]),
 array([[-0.80774452],
        [ 0.17820321]]),
 array([[-0.18650636]]))

In [17]:
output0 = X
outputHidden = seg(np.dot(output0 , wh)+bh)
#this is the dot mtrix multiplicaion of (4,2) matrix to (2,2) weight matrix of hidden layer
output = seg(np.dot(outputHidden , wo)+bo)
output

array([[0.35615174],
       [0.34428082],
       [0.38568049],
       [0.37107225]])